#!/bin/sh /etc/rc.common
# WeRead Selenium Auto Start

START=99
STOP=10

start() {
    echo "Starting WeRead Selenium..."
    while ! docker ps >/dev/null 2>&1; do
        sleep 2
    done
    cd /mnt/sata1-1/docker/mycontainers/weread-challenge-selenium-muti-user && docker compose up -d selenium
}

stop() {
    echo "Stopping WeRead Selenium..."
    cd /mnt/sata1-1/docker/mycontainers/weread-challenge-selenium-muti-user && docker compose down
}
